### ISSUE TITLE
The issue of contributing

### ISSUE THREAD

**Issue by skmd0** [Bennylavaa/pfQuest-epoch#26]
First of all, massive respect for making this addon. For a lot of people quest addon is essential.

I have been thinking of the overwhelming amount of work necessary to manually add all the custom content. I have been trying to contribute to this project a bit, but it takes me more than 30 mins for a single quest. I am not sure how much content did Project Epoch add, but it feels like a daunting job.

It could be sped up if more people contributed to this addon, but the barriers to entry are huge for an average WoW player. They need to know git, they need to figure out how different files connect to each other, they need to be careful with extracting the correct information etc.. Not sure what the solution is.

Is there no way Project Epoch devs could dump custom content data so we could parse through it?

**Comment by Bennylavaa** [comment]
they already told me no they will not be giving us a dump so they will have to be added by hand.

**Comment by Bennylavaa** [comment]
The best way to learn is to look up regular vanilla quests in the base pfquest and see how everything has been done. Unfortunately, that is really the only way to learn how to add stuff to this DB addon. 

The best course of action would be to have maybe 10 people working on this addon during beta but I doubt we will get more than is already working on it. pfquest-turtle was the same until the turtle team broke down and gave us the DB to import into pfquest

**Comment by skmd0** [comment]
> they already told me no they will not be giving us a dump so they will have to be added by hand.

Ah, that is unfortunate. I guess the current way of doing thing is the best right now.
